version: '3.8'

services:
  book-api:
    container_name: book-api
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./book_api/books_with_country.json:/app/book_api/books_with_country.json
    environment:
      - PYTHONUNBUFFERED=1
